version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - apt-get update
      - apt-get install -y unzip
      - wget https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
      - unzip terraform_1.0.11_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  build:
    commands:
      - echo "Starting build phase"
      - terraform init
      - terraform apply -auto-approve 
